---
title: "PD-R-Py Praca Domowa nr 4"
author: "Kamil Grabowski, Piotr Luboń"
date: "May 26, 2018"
output: ioslides_presentation
runtime: shiny
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
source('plot_helpers.R')
data <- readRDS('agg_data2.Rds')
options(scipen=10)
```

## Średnie opóźnienia w poszczególnych miesiącach

```{r, echo=FALSE}
files_m <- list.files('results_months')

data2 <-  read.csv(file.path('results_months', files_m[2]))

for(i in 3:length(files_m)){
  data_temp <- read.csv(file.path('results_months', files_m[i]))
  data2 <- data2 + data_temp
}
data2['DepDelayAvg'] <- data2['DepDelayAvg']/(length(files_m)-2)
plot.default(data2['DepDelayAvg'], xlab = 'Miesiąc', ylab = 'Średnie opóźnienie')
```

## Opóźnienia większe niż 15 min w 2008

```{r, include=FALSE}
library(ggplot2)

files <- list.files('month_routes')
col_from_per <- function(p)
{
  ifelse(p <= 10, 1, ifelse(p <= 15, 2, ifelse(p <= 20, 3, ifelse(p <= 25, 4, 5))))
}
plot_routes_percent <- function(routes)
{
  routes$percent <- as.factor(col_from_per(routes$percent))
  worldmap <- borders("world",xlim = c(-200, -20), ylim = c(20, 55), colour="#efede1", fill="#efede1") # create a layer of borders
  ggplot() + worldmap +
    geom_curve(data=routes, aes(x = from.lon, y = from.lat, xend = to.lon, yend = to.lat, colour = percent),  size = 0.2, curvature = .2) + 
      scale_colour_manual(labels= c('<= 10 %', '10% - 15%', '15% - 20%', '20% - 25%', '>25%'), 
                         values=c('green', 'purple', 'blue', 'orange', 'red'))+
    theme(panel.background = element_rect(fill="white"), 
          axis.line = element_blank(),
          axis.text.x = element_blank(),
          axis.text.y = element_blank(),
          axis.ticks = element_blank(),
          axis.title.x = element_blank(),
          axis.title.y = element_blank(),
          legend.title = element_blank(),
          legend.position = 'left'
    ) 
}
```

```{r eruptions}
inputPanel(
  
sliderInput('month', 'Month', min=1, max=12,
                value=1, step=1, round=0)
)

renderPlot({plot_routes_percent(read.csv(file.path('month_routes',
                                                                     paste(as.character(input$month), '.csv', sep = ''))))
  })
```

## Liczba lotów na przestrzeni lat
```{R, echo=FALSE}
yearly_data <- loty_w_latach(data)
plot(yearly_data$rok, yearly_data$liczba_lotow, xlab='Rok', ylab='Liczba Lotów')
```


## Opóznienia na przestrzeni lat
```{R, echo=FALSE}
plot(yearly_data$rok, yearly_data$dep_delay, xlab='Rok', ylab='Srednie opoznienie', col='skyblue', type = 'l',
     ylim=c(min(yearly_data$arr_delay), max(yearly_data$dep_delay)))
lines(yearly_data$rok, yearly_data$arr_delay, col='orangered')
```

## Który przewoźnik najmniej się spóźnia?
```{r, echo=FALSE,results='hide',fig.keep='all'}
carrier_data <- delay_by_carrier(data)
carrier_data_long <- carrier_data[lapply(carrier_data, nrow)>15]
par(mfrow=c(3,3))
ylim_min <- min(unlist(lapply(carrier_data_long, function(x){return(min(x$dep))})))
ylim_max <- max(unlist(lapply(carrier_data_long, function(x){return(max(x$dep))})))
lapply(carrier_data_long, function(x, arg1, arg2)
  {
    plot(x$year, x$dep, type = 'b', xlab='Rok', ylab ='Srednie opoznienie wylotu', main=x[1,'UniqueCarrier'],ylim=c(arg1, arg2))
  }, arg1=ylim_min, arg2=ylim_max)
```

## Który przewoźnik najmniej się spóźnia?
```{r,echo=FALSE,results='hide',fig.keep='all'}
carrier_data <- delay_by_carrier(data)
carrier_data_long <- carrier_data[lapply(carrier_data, nrow)>15]
par(mfrow=c(3,3))
ylim_min <- min(unlist(lapply(carrier_data_long, function(x){return(min(x$arr))})))
ylim_max <- max(unlist(lapply(carrier_data_long, function(x){return(max(x$arr))})))
lapply(carrier_data_long, function(x, arg1, arg2)
  {
    plot(x$year, x$arr, type = 'b', xlab='Rok', ylab ='Srednie opoznienie przylotu', main=x[1,'UniqueCarrier'],ylim=c(arg1, arg2))
  }, arg1=ylim_min, arg2=ylim_max)
```

## Piątek trzynastego
```{r, echo=FALSE}
unlucky <- avg_delay_unlucky(data)
test_results <- get_test_results(data, unlucky)
kableExtra::kable(rbind(unlucky[1:2], test_results[1,]))
```

## Wtorek trzynastego
```{r, echo=FALSE}
kableExtra::kable(rbind(unlucky[3:4], test_results[2,]))
```

## Piątek siedemnastego
```{r, echo=FALSE}
kableExtra::kable(rbind(unlucky[5:6], test_results[3,]))
```

